### ISSUE TITLE
Completed ATIP request page does not allow anonymous submission

### ISSUE THREAD

**Issue by obrien-j** [obrien-j/gc_musings#1]
The form at open.canada.ca allows for ATIP requests that have already been completed and delivered to the original requestor to be requested again by anyone. This form gives several options for identifying oneself, with one option being 'Decline to identify'.

The web form itself does not change to respond to the option chosen. The form in its default state forces the majority of the names/address to be marked as 'required' from a form submission perspective.

If there is in fact a desire to allow for anonymous submissions then a potential solution would be to use some js to simply rewrite the displayed fields to mark most as not required. Alternatively, convert the http form to a simple ajax request taking data from specific fields as necessary.

Submitted feedback to the Open Gov team on April 20st, 2017. 
Received confirmation of issue and the team confirmed they'd follow up with ATIP and come back to me, april 21st, 2017
Reached back out to the open gov team to follow up on the issue, may 10th 2017.

**Comment by obrien-j** [comment]
Issue is with IPPD group within TBS. Open Gov team was unable to provide a contact within team to discuss the issue. #waiting

**Comment by TanyaSpydergrrl** [comment]
Hey - Decline to identify refers to the "type" of requester. Not identity. However, we are in the process of re-evaluating how much Identity information we need from requesters for the different types of requests (new ATI request, new PI request, request for previously release ATI request). As such, we are re-evaluating what constitutes the minimum tombstone info for each request type.

The Open Gov form is currently out of scope for the initial release of the new ATIP site (March 2018), however I have captured this issue so we can include it in the scope of a later release.

Thanks for flagging it!

**Comment by obrien-j** [comment]
@TanyaSpydergrrl That makes sense but is not a great UX flow to be honest... That being said, unless there's some law that prevents arbitrary canadians from requesting completed ATI requests, then re-publishing them, what's the point really?

**Comment by TanyaSpydergrrl** [comment]
Not sure what you mean about the flow. The release packages are not posted online, so some amount of contact information is required by the department to provide the package. For a digital copy (current provided by either email or CD, depending on size) we need at minimum an email address. If the requesters wants the information in dead tree form, we need a name and address. At this time, the release packages are not available to download in digital format but when we implement the data standards project, everyone will have to provide accessible digital formats. At that time, we will build the web infrastructure to enable citizens to download their request packages, and we will determine whether request packages should be posted as open data in the first place.

**Comment by obrien-j** [comment]
Was just referring to the association I made between 'decline to identify', followed by a form that forced me to fill out all my personal information.

I've had a request rejected for electronic transmission with only email provided recently. Not the end of the world, but there does seem to be a disconnect between what dept's need, and what information can truly be verified. This feels like a #digitalidentity problem. ;)

Looking forward to the new rollout you're working on!

**Comment by TanyaSpydergrrl** [comment]
Gotcha. That's exactly why we need to review the data requirements to make sure they're commensurate with the request. 

And yes, now I see why that would be confusing. Will make a note. :)
