### ISSUE TITLE
Requesting completed ATIP requests is very inefficient

### ISSUE THREAD

**Issue by obrien-j** [obrien-j/gc_musings#2]
Until recently, there was no drop-down option for Delivery Method.. There now exists options for mailed delivery, electronic delivery, and in-person viewing..

It appears odd that these ATIP requests would not simply be hosted as a downloadable link. The resulting process of submitting a request currently goes to a person, who then has to either mail (burnt to a CD), or email a file to the requestor.

This process is no different than clicking a button and receiving a file instantly.

When I last requested this option, I was told that due to Official Languages policy, the government was unable to host the non-translated information. This is an unfortunate interpretation of OL as they are still providing the files directly to the requestor upon request, simply via an inefficient manual method. According to 12 (2) (b) of the Access to Information Act, it appears the requestor can request the record in their choice of language, provided 'head of the government institution' considers it is in the public interest to have a translation completed.

This ticket is to track my progress through encouraging the ATIP community to simply publish a link to the completed requests for download, and to document the reasons why this doesn't break OL policies.

**Comment by obrien-j** [comment]
I'm seriously tempted to write a 5 line python script, to request every single completed ATI request, and then simply publishing them in a public github repository. It's a saturday and I am not firing on all cylinders. How many ATIP staff could I break in under 2 seconds? 

[This is entirely a joke, i will not do this. It's insane. But I could. Which is also insane.]

**Comment by TanyaSpydergrrl** [comment]
The website and backend systems are not connected. The Open Gov team forwards the request to the receiving department, who then uses whatever system they have in place (manual, case management system, paper files) to pull the request and deliver it to the intended recipient. Until we have data standards for ATIP data (and the required supporting technical infrastructure), historical requests will continue to be processed by hand. We're starting with redesigning the request intake, and then we will move to standardizing the data, which will enable us to increase the functionality on the site: users will eventually be able to download digital packages, and posting them to Open Gov will be much easier.

**Comment by obrien-j** [comment]
I'm going to just add this here for further background on this issue, specifically related to the original rational provided.

Taken from the "open by default pilot", http://pilot.open.canada.ca/en/pilote-ouverture-par-defaut .

"Note: The Open by Default Pilot provides access to working documents used by the Government of Canada. Most of this information is unpublished and may include errors or omissions. Many documents will be in draft form, are generally available in the language in which they were created, and may not be fully accessible. Unless otherwise indicated, information is made available under the Open Government Licence. To obtain documents in the official language of your choice, or in an accessible format, please contact us."

Taken again with a grain of salt, it seems as if this same wording/risk tolerance would be sufficient to deliver the completed ATI requests in a online form. 

I would be very interested in anyone's take on this from an OL or accessibility perspective, as I feel like there are also interesting automated options that could be investigated to better meet everyone's needs.
