### ISSUE TITLE
open.canada.ca form submission for completed atip requests does not appear to be encrypted

### ISSUE THREAD

**Issue by obrien-j** [obrien-j/gc_musings#7]
[Example completed ati request](http://open.canada.ca/forms/contact-ati-org?org=Shared%20Services%20Canada&req_num=A-2016-00135&disp=Disclosed%20in%20part&year=2017&month=January&pages=258&req_sum=All%20briefing%20notes%2C%20reports%2C%20memoranda%2C%20e-mails%20and%20other%20documents%2C%20including%20drafts%2C%20written%20by%20or%20received%20by%0AShared%20Services%20Canada%20employees%20concerning%3A%20in%20year%20financial%20transfers%20from%20Statistics%20Canada%20to%20Shared%0AServices%20Canada%20to%20acquire%20services.%20For%20the%20period%20April%201%2C%202016%20to%20September%2030%2C%202016.&req_pages=258&email=ATIP-AIPRP@ssc-spc.gc.ca)

Noticed while submitting an ATI request that the form submission appears to be over an unencrypted http session....

Given the full address, tele, email, name information which is arguably personal information... This form submission should be sent to an encrypted HTTPS endpoint. The entire site should technically be wrapped in encrypted TLS sessions.... I believe there's direction from TBS on that matter specifically.

**Comment by TanyaSpydergrrl** [comment]
I have brought this one up with my manager. Since the site is out of our scope, not sure how much we can do in short order. However we will definitely consider this issue as we work on redesigning the form.

**Comment by obrien-j** [comment]
![opendata_tls_sadface](https://user-images.githubusercontent.com/17616596/27513605-06c8687e-593a-11e7-9c30-9382670295c2.JPG)

Given that this is just a simple CKAN (pylon / flask) app set up behind what is likely an Apache or nginx server, it's very likely about 2-3 lines in the config file to sort this out.  This assumes you have a certificate for the site already, but even that takes an hour to sort out.

If you're lacking for IT folks, I'd be glad to assist.

**Comment by TanyaSpydergrrl** [comment]
Yes, they've got issues with their security certificate as well. However, the Open site isn't ours. You can always chat with the Open Gov folks about issues related to their site (which is hosted and maintained by Service Canada).

**Comment by obrien-j** [comment]
![open_secure](https://user-images.githubusercontent.com/17616596/35646752-311d15a4-069e-11e8-9c85-97d9fa7641b4.PNG)

👍
